// Repo operations SDK — high-level functions for working with GitRepo
export {
	blame,
	countAheadBehind,
	createCommit,
	createSandboxWorktree,
	createWorktree,
	diffCommits,
	diffTrees,
	extractTree,
	findMergeBases,
	flattenTree,
	getChangedFiles,
	getNewCommits,
	grep,
	isAncestor,
	listBranches,
	listTags,
	mergeTrees,
	mergeTreesFromTreeHashes,
	overlayRepo,
	readBlob,
	readBlobText,
	readCommit,
	readFileAtCommit,
	readonlyRepo,
	resolveRef,
	walkCommitHistory,
	writeBlob,
	writeTree,
	type BlameEntry,
	type CommitInfo,
	type CreateCommitOptions,
	type CreateWorktreeOptions,
	type DiffHunk,
	type ExtractTreeResult,
	type FileDiff,
	type GrepFileMatch,
	type GrepMatch,
	type GrepOptions,
	type MergeConflict,
	type MergeTreesResult,
	type TreeEntryInput,
	type WorktreeResult,
} from "./helpers.ts";

// Re-exported lib types used in helper signatures
export type { Commit, GitRepo, Identity, RefEntry, TreeDiffEntry } from "../lib/types.ts";
export type { FlatTreeEntry } from "../lib/tree-ops.ts";
