// Scans src/lib/**/*.ts and src/format/**/*.ts and extracts all exported
// symbols, then prints a markdown file reference to stdout.
//
// Usage: bun scripts/gen-lib-reference.ts > docs/FILE_REFERENCE.md

import { relative, resolve } from "node:path";
import { Glob } from "bun";

const ROOT = resolve(import.meta.dir, "..");
const LIB_DIR = resolve(ROOT, "src/lib");
const FORMAT_DIR = resolve(ROOT, "src/format");

interface FileExports {
	functions: string[];
	classes: string[];
	types: string[];
	interfaces: string[];
	enums: string[];
	consts: string[];
	reExports: string[];
}

function extractExports(source: string): FileExports {
	const result: FileExports = {
		functions: [],
		classes: [],
		types: [],
		interfaces: [],
		enums: [],
		consts: [],
		reExports: [],
	};

	const lines = source.split("\n");

	function cap1(m: RegExpMatchArray): string {
		return m[1] as string;
	}

	for (let i = 0; i < lines.length; i++) {
		const line = lines[i] as string;

		if (!line.startsWith("export ")) continue;

		// export { Foo, Bar } or export type { Foo, Bar } — may span lines
		const groupedMatch = line.match(/^export\s+(?:type\s+)?\{(.*)$/);
		if (groupedMatch) {
			let block = cap1(groupedMatch);
			while (!block.includes("}") && i + 1 < lines.length) {
				i++;
				block += ` ${lines[i] as string}`;
			}
			block = block.replace(/}.*$/, "");
			const names = block
				.split(",")
				.map((s) => s.trim())
				.filter((s) => s.length > 0)
				.map((s) => s.replace(/\s+as\s+\w+/, ""));
			result.reExports.push(...names);
			continue;
		}

		const matchers: [RegExp, string[]][] = [
			[/^export\s+(?:async\s+)?function\s*\*?\s*(\w+)/, result.functions],
			[/^export\s+class\s+(\w+)/, result.classes],
			[/^export\s+enum\s+(\w+)/, result.enums],
			[/^export\s+interface\s+(\w+)/, result.interfaces],
			[/^export\s+type\s+(\w+)\s*=/, result.types],
			[/^export\s+const\s+(\w+)/, result.consts],
		];
		for (const [re, arr] of matchers) {
			const m = line.match(re);
			if (m) {
				arr.push(cap1(m));
				break;
			}
		}
	}

	return result;
}

function sortKey(rel: string): string {
	// lib/*.ts first, then lib/objects/*.ts, lib/transport/*.ts, then format/*.ts.
	if (rel.startsWith("format/")) return `3_${rel}`;
	const libRel = rel.slice("lib/".length);
	let prefix: string;
	if (libRel.startsWith("objects/")) prefix = "1_";
	else if (libRel.startsWith("transport/")) prefix = "2_";
	else prefix = "0_";
	return prefix + rel;
}

function formatExports(exp: FileExports): string[] {
	const lines: string[] = [];

	if (exp.functions.length > 0) {
		lines.push(`- ${exp.functions.map((f) => `\`${f}\``).join(", ")}`);
	}
	if (exp.classes.length > 0) {
		lines.push(`- **classes**: ${exp.classes.map((c) => `\`${c}\``).join(", ")}`);
	}
	if (exp.consts.length > 0) {
		lines.push(`- **consts**: ${exp.consts.map((c) => `\`${c}\``).join(", ")}`);
	}
	if (exp.enums.length > 0) {
		lines.push(`- **enums**: ${exp.enums.map((e) => `\`${e}\``).join(", ")}`);
	}
	if (exp.interfaces.length > 0) {
		lines.push(`- **interfaces**: ${exp.interfaces.map((i) => `\`${i}\``).join(", ")}`);
	}
	if (exp.types.length > 0) {
		lines.push(`- **types**: ${exp.types.map((t) => `\`${t}\``).join(", ")}`);
	}
	if (exp.reExports.length > 0) {
		lines.push(`- **re-exports**: ${exp.reExports.map((r) => `\`${r}\``).join(", ")}`);
	}

	return lines;
}

async function main() {
	const glob = new Glob("**/*.ts");
	const files: { absPath: string; rel: string }[] = [];

	for await (const path of glob.scan({ cwd: LIB_DIR, absolute: true })) {
		files.push({ absPath: path, rel: `lib/${relative(LIB_DIR, path)}` });
	}
	for await (const path of glob.scan({ cwd: FORMAT_DIR, absolute: true })) {
		files.push({ absPath: path, rel: `format/${relative(FORMAT_DIR, path)}` });
	}

	files.sort((a, b) => sortKey(a.rel).localeCompare(sortKey(b.rel)));

	const sections: string[] = [];

	sections.push("# Lib File Reference");
	sections.push("");
	sections.push(
		"Exported symbols from `src/lib/` and `src/format/`. Generated by `bun scripts/gen-lib-reference.ts`.",
	);

	for (const { absPath, rel } of files) {
		const source = await Bun.file(absPath).text();
		const exp = extractExports(source);

		const formatted = formatExports(exp);
		if (formatted.length === 0) continue;

		sections.push("");
		sections.push(`### ${rel}`);
		sections.push("");
		sections.push(...formatted);
	}

	process.stdout.write(`${sections.join("\n").trimEnd()}\n`);
}

main();
